/*======================================================================*
 * PROJECT:         MF-DECODER
 * MODUL:           SCHEDULER
 * DEVELOPED BY:    Christoph Klie
 * FILENAME:        scheduler.c
 *
 * DESCRIPTION:
 *      SCHEDULER SOURCE FILE
 *      THE SCHEDULER GIVES A BASIC TIMING FUNCTIONALITY TO THE USER
 *      WITH A RESOLUTION AT 0,1 SECONDS AND THE OPPORTUNITY FOR SETTING
 *      A MONITOR LED WITH AUTOMATIC FALLBACK
 *
 * (C) COPYRIGHT 2015 - CHRISTOPH KLIE
 *======================================================================*/

#include "scheduler.h"

/*
 * USING FASTER MEMORY FOR FASTLY REPEATING CALCULATIONS
 */
#define SCHEDULER_HIGH_BYTE         __MEMORY_DRIVER_IOMEM_R0
#define SCHEDULER_TIME_PASSED       __MEMORY_DRIVER_IOMEM_R1
#define SCHEDULER_MONITOR_LED_CTC   __MEMORY_DRIVER_IOMEM_R2

/*
 * INTERRUPT FUNCTION PROTOTYPE
 */
static void SCHEDULER_INTERRUPT_CTC(void);

/*
 * INITIALIZE SCHEDULER AND START TIMING OPERATION
 */
void SCHEDULER_INITIALIZE(void)
{
    SCHEDULER_HIGH_BYTE = 0x00;
    SCHEDULER_TIME_PASSED = 0x00;

    GPIO_LED_RD_INIT();
    GPIO_LED_RD_OFF();

    __TIMER0_DRIVER_TCNT = 0x00;
    __TIMER0_DRIVER_MODE_CTC();
    __TIMER0_DRIVER_INTERRUPT_COMPA_SETFUNC(SCHEDULER_INTERRUPT_CTC);
    __TIMER0_DRIVER_INTERRUPT_COMPA_ENABLE(244);
    __TIMER0_DRIVER_CLOCK_DIV1024();
}

/*
 * ENABLE THE MONITOR LED AND SET TIME WHEN IT IS SUPPOSED TO TURN OFF
 */
void SCHEDULER_MONITOR_LED_SET(void)
{
    GPIO_LED_RD_ON();
    SCHEDULER_MONITOR_LED_CTC = SCHEDULER_TIME_PASSED + 10;
}

/*
 * SET VARIABLE FOR TIMING SETTINGS
 * THIS VARIABLE SET THE STARTING POINT OF THE TIME CALCULATION
 * THE USER CAN RETRIEVE THE TIME INTERVALL BETWEEN THIS CALL AND THE NEXT GET REQUEST
 */
void SCHEDULER_SECONDS_SET_TIME(unsigned char *TimeStart)
{
    *TimeStart = SCHEDULER_TIME_PASSED;
}

/*
 * GET PASSED TIME BETWEEN VARIABLE SET AND THIS FUNCTION CALL
 */
unsigned char SCHEDULER_SECONDS_GET_TIME(unsigned char *TimeStart)
{
    return (SCHEDULER_TIME_PASSED - (*TimeStart));
}

/*
 * INTERRUPT FUNCTION FOR COUNTING UP THE SCHEDULER
 * SCHEDULER RESOLUTION IN 0,1S
 * AUTOMATICALLY TURNS OFF THE MONITOR LED AFTER EXPIRATION
 */
static void SCHEDULER_INTERRUPT_CTC(void)
{
    if(++SCHEDULER_HIGH_BYTE == 8)
    {
        SCHEDULER_HIGH_BYTE = 0x00;

        if((++SCHEDULER_TIME_PASSED) == SCHEDULER_MONITOR_LED_CTC)
        {
            GPIO_LED_RD_OFF();
        }
    }
}
